name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello"

  checkmarx:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "hello"
      
  temp-deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - run: echo "hello"
      
  acceptance-tests:
    runs-on: ubuntu-latest
    needs: [temp-deploy]
    
    steps:
      - run: echo "hello"

  create-release:
    runs-on: ubuntu-latest
    needs: [build, temp-deploy, acceptance-tests, checkmarx]
    
    steps:
      - run: echo "hello"
